// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: record.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRecord = `-- name: CreateRecord :exec
INSERT INTO records(account_id, time)
VALUES ($1, $2)
`

type CreateRecordParams struct {
	AccountID uuid.UUID
	Time      float32
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) error {
	_, err := q.db.Exec(ctx, createRecord, arg.AccountID, arg.Time)
	return err
}

const getAllRecord = `-- name: GetAllRecord :many
SELECT id, account_id, time, created_at
FROM records
`

func (q *Queries) GetAllRecord(ctx context.Context) ([]Record, error) {
	rows, err := q.db.Query(ctx, getAllRecord)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Time,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
